// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BurgerMenuController from "./burger_menu_controller"
application.register("burger-menu", BurgerMenuController)

import ChatboxSubscriptionController from "./chatbox_subscription_controller"
application.register("chatbox-subscription", ChatboxSubscriptionController)

import DisplayeventController from "./displayevent_controller"
application.register("displayevent", DisplayeventController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
