meta_name: "Fit Mate"
meta_title: "Fit Mate - Rencontre des potes pour faire du sport !"
meta_description: "Fit Mate est l'application de rencontre sportive pour tous. Adapté à votre niveau et axé avant tout sur des évênements sportifs permettant de rencontrer de nouvelles personnes."
meta_image: "logo-fitmate.png" # should exist in `app/assets/images/`
